settings:
  title: 'Status Page'
  url: 'https://status-page.xxr99.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: railway-aria2-cf # unique identifier
    name: railway.aria2.cf
    description: 'railway项目' # default=empty
    url: 'https://rail-aria.xxr99.workers.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: wink&blog
    name: wink的快乐小博客
    description: '博客快乐本体！'
    url: 'http://wink.winkxrq.tk'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: moyun
    name: 快乐默云
    url: 'http://v2.winkx.ga'
    method: GET
    expectStatus: 200
